### ISSUE TITLE
Consulta ejercicio de Final

### ISSUE THREAD

**Issue by DamoFernandez** [AnalisisDeSistemasPiccirilli/foro#11]
Buenas tardes,

Estuve buscando algunos modelos de finales y me encontré con una preguntas respecto a la practica, los cuales no supe a que se refería.

Dicho ejercicio se relacionaba con las "Reglas Otras" para Tablas de Decisión. 

Cuales serian dichas reglas, a que hacen referencia y como puedo reconocerlas?

Muchas gracias.
Saludos,
Damián.

**Comment by schmidtdiego** [comment]
Hola Damián, la regla "otras" es una regla especial que se puede agregar al
final de la tabla de decisión, y que permite representar todas las reglas
que no estén contempladas explícitamente en la tabla.

Por ejemplo, en una tabla binaria con 3 condiciones, tenemos en total 8
reglas.
Podríamos armar una tabla que represente sólo 5 reglas, y agregar la regla
"Otras" al final, que represente los 3 casos faltantes de la tabla.
Siempre se incluye como última regla de la tabla, en la parte de
condiciones tiene la palabra "OTRAS", y en la parte de acciones tiene las
marcas de acción que se ejecutarían en los casos que no están definidos a
su izquierda.
Cuando no se usa la regla "otras", la tabla debe representar todos los
casos posibles en sus reglas, que es la forma de construcción que
utilizamos nosotros durante la cursada.
Esto es porque consideramos que el uso de la regla "otras" presenta la
desventaja de no "obligar" al analista a analizar caso por caso todas las
reglas posibles, lo cual contribuye a que haya errores u omisiones de
análisis en la lógica de la decisión.
El tema fue comentado en clase cuando hablamos del final de la materia.
Pueden encontrar más información al respecto en la bibliografía recomendada
del tema.

Saludos!

Diego

**Comment by DamoFernandez** [comment]
Muchas gracias Diego!
