### ISSUE TITLE
Duda sobre clave en DER

### ISSUE THREAD

**Issue by julian-0** [AnalisisDeSistemasPiccirilli/foro#9]
Hola a todos, me quedo una duda colgada sobre DER.
Cuando teníamos una entidad de dirección, que clave elegíamos?
Calle, altura, piso, departamento y código postal o le asignábamos un código de dirección para usarlo como clave?

Saludos

**Comment by thehighestprimenumber** [comment]
Hola, en clase venimos utilizando una clave subrogada ("codigo_direccion" o
similar). De otro modo, cada entidad que se relaciona con una dirección
debería tener todos sus atributos, perdiendo el sentido de la normalización.
Recorda además, que no es recomendable usar cadenas de texto como clave
primaria.

**Comment by nahueldl** [comment]
El problema de usar "Calle, altura, piso, departamento y código postal" es que existe la gran posibilidad de que un cliente viva en una casa y no posea ni piso ni departamento, y te recuetdo que en DER **los atributos que componen la clave no pueden ser nulos**, por este motivo se reduciría la clave a "Calle, altura y código postal" pero en este caso no podrías tener 2 clientes que vivieran en el mismo edificio.
Por su supuesto habría que ver la problemática del ejercicio en particular, pero por este motivo es que en general utilizamos como clave un codigo_direccion o idDireccion.

**Comment by julian-0** [comment]
Muchas gracias a ambos !!
